### ISSUE TITLE
Bug in GenerateInputFilesParametric with special coherence strings

### ISSUE THREAD

**Issue by ewanmac** [ebranlard/weio#2]
anaconda3/envs/weio/bin/python 
turbsim2/scripts/Main02_GenerateInputFilesParametric.py
Traceback (most recent call last):
turbsim2/scripts/Main02_GenerateInputFilesParametric.py", line 34, in <module>
    input_files = fastlib.templateReplaceGeneral(PARAMS, output_dir=output_dir, main_file=main_file)
  File "/home/ewan/mount/home/pve/wp1/third-party/welib/welib/fastlib/fastlib.py", line 687, in templateReplaceGeneral
    Files['ROOT']=weio.FASTInFile(fst_full)
  File "weio/weio/FASTInFile.py", line 41, in __init__
    super(FASTInFile, self).__init__(filename=filename,**kwargs)
  File "weio/weio/File.py", line 23, in __init__
    self.read()
  File "weio/weio/File.py", line 38, in read
    self._read()
  File weio/weio/FASTInFile.py", line 352, in _read
    raise WrongFormatError('Special Character found in Label: `{}`'.format(d['label']))
weio.File.WrongFormatError: Special Character found in Label: `0.000659"`

--------Spatial Coherence Parameters----------------------------
"IEC"	SCMod1		- u-component coherence model ("GENERAL","IEC","API","NONE", or "default")
"IEC"	SCMod2		- v-component coherence model ("GENERAL","IEC","NONE", or "default")
"IEC"	SCMod3		- w-component coherence model ("GENERAL","IEC","NONE", or "default")
**"12.0 0.000659"**	InCDec1	- u-component coherence parameters for general or IEC models [-, m^-1] (e.g. "10.0  0.3e-3" in quotes) (or "default")
**"12.0 0.000659"**	InCDec2	- v-component coherence parameters for general or IEC models [-, m^-1] (e.g. "10.0  0.3e-3" in quotes) (or "default")
**"12.0 0.000659"**	InCDec3	- w-component coherence parameters for general or IEC models [-, m^-1] (e.g. "10.0  0.3e-3" in quotes) (or "default")
"0.0"	CohExp		- Coherence exponent for general model [-] (or "default")

**Comment by ebranlard** [comment]
Hi Ewan,

Sorry for my very long answer on this. The trick is to replace the space by a comma, in the inputs `InCDec1` `InCDec2` `InCDec3`, in your example "12.0,0.000659" for 
instance. It's unfortunate that this input was set as a string. 

The same holds for other OpenFAST inputs that are list of numbers, they need to be separated by commas (but without the quotes which are specific to these TurbSim inputs). 

Cheers,

Emmanuel
