### ISSUE TITLE
Module import issue

### ISSUE THREAD

**Issue by kpramng** [ebranlard/weio#22]
Hi,

I followed the below instructions to install weio and used the code [https://github.com/ebranlard/weio/blob/main/examples/Read_FASTOut.py](url) to read the contents of a .out file, but returned the following error. I ran the python script in Spyder.

Any help is highly appreciated.

`git clone https://github.com/ebranlard/weio
cd weio
python -m pip install --user -r requirements.txt  
python -m pip install -e .      # install
python -m unittest discover -v  # run test`

![image](https://user-images.githubusercontent.com/110171497/195303397-8429be5e-3b3b-4fe8-a336-83fa086030e2.png)

Best regards,
Karthik

**Comment by kpramng** [comment]
@ebranlard  Is the above something to do with running in Spyder. I followed the steps and for some reason it cannot find the module.

**Comment by ebranlard** [comment]
It's possible, maybe spyder is using a special environment. You can try to ask spyder to open a command line for you and redo the steps.

**Comment by kpramng** [comment]
@ebranlard Thanks for getting back. Will try that out and keep you posted.

**Comment by ebranlard** [comment]
Hi @kpramng

Let us know if this is still an issue or what you did to solve it.
